### ISSUE TITLE
Pop panel manager and Fenix

### ISSUE THREAD

**Issue by Rotorxdan** [hawkeye-stan/msfs-popout-panel-manager#93]
Hi everybody, I have been running up until the last update msfspopout panel with FBW A32nx, without a problem. Today decided to try Fenix A320 and basically I ended up empty handed.... When I try to identify a panel, the corresponding coloured circle is placed, let's say on the PFD but all  the values remain at 0, like there would be no panel. And when I mean 0 is not only the position, is also the size of the intended popout. I have followed the exact same procedure as with FBW, but here I can't figure out what the problem is. Thanks

**Comment by hawkeye-stan** [comment]
Once you've identify the panels with the colored circles, you've to execute "start pop out" once before top, left, width, and height will have values since POPM will need to know the initial pop outs location so you can configure and save them.

**Comment by Rotorxdan** [comment]
Thanks, that is solved. Now the problem I am having is that I select the PFD, ND and Ecams, and the popout process adds the Flypad without having being selected. Funny enough the PFD is popped out but in the list its position is being replaced by the Flypad popout. The circle selecting the screen is in the right place but the popped panel does not correspond. In addition all popouts have the name previously given, but the PFD one has WASMinstrument in its window title, and the FLYpad has the PFD name. If I restart everything the PFD does not come up but the Flypad yes. Sorry for the confusion ....

**Comment by hawkeye-stan** [comment]
You've run into one of the hard to catch bug in MSFS, sometimes, the panel popped out is not the one you want. During POPM  pop out process, each colored circle for the panel will briefly appear. Do they each correspond to the panel you configured?

**Comment by Rotorxdan** [comment]
Sorry for the late answer. Let me try to explain what is currently happening. When the pop out process starts, the coloured circle is placed over the PFD, but what comes on the monitor is the Flypad. Towards the end of the process when the time is that the circle goes over the Flypad, the PFD shows up on the monitor. The rest of the screens are every single time misaligned. I have restarted, repositioned, but it looks like the final placement is rather random. I can resize and move the panels, but not the original Flypad that appears over the PFD monitor. A true mess.

**Comment by hawkeye-stan** [comment]
If when POPM try to execute the pop out for PFD (circle placement is correct as stated) by emulating Right-Alt Left-Click keystroke, it somehow pops out Flypad, then there is a bug in the game. If you manually pop out PFD, does this issue happen? I remember a while back, this bug happened on the regular A320 and there no one can figure out the real cause.

Here is a possible fix. Try changing the sequence of pop outs in POPM. Pop your flypad first before PFD. You can change the sequence by using the mouse to drag the panel definition and move Flypad before PFD.

Or just switch the naming of panel definitions for the panels for POPM since Flypad is PFD and PFD is Flypad.

<img width="743" alt="image" src="https://github.com/hawkeye-stan/msfs-popout-panel-manager/assets/72271266/f1ff18d9-8294-4bea-aab4-30d3e52f3401">

**Comment by Rotorxdan** [comment]
Ok, let's see.... Right ALT+Left click brings the Flypad when done over the PFD.
Changing the order, (even deleting and adding new panel) brings PFD and ND error on popping .

**Comment by Rotorxdan** [comment]
Hi, I have realised another thing, the Flypad most of the times appears on the first POPout, that is, I did place the exams first and to my surprise the upper ecam got the the flypad and later PFD and ND popped out correctly.

**Comment by hawkeye-stan** [comment]
This is so weird, something seems off with Fenix. I know the regular A320 have similar bug a year ago and I thought the bug was fixed in MSFS. Maybe it is still there and affecting you somehow.

**Comment by Rotorxdan** [comment]
As long as I don't loose my patience, I will keep on trying different things. Thanks for your help. Keep you posted.

**Comment by hawkeye-stan** [comment]
You can try going back to previous version 4.0.1.2 of POPM. Just download the zip and overwrite the new one. It could be the latest version of POPM does not work correctly Fenix. As of now, I've not received report from users of Fenix encountering your issue yet so your problem is hard to pinpoint. And since I don't have the aircraft to test, I'm not sure what could be causing your issue. I'll keep this topic alive and maybe I'll get problem report by other Fenix users and I'll be able to identify your issue..

**Comment by Rotorxdan** [comment]
I did go back to the previous version and the problem remains the same. Do you want me to record a video so you can see better what is going on?

**Comment by hawkeye-stan** [comment]
Looks like it is not the new version of POPM that causes the issue. Somehow, the Fenix aircraft no longer works. Can you manually pop out panels correctly without POPM?

**Comment by Rotorxdan** [comment]
For the times I tested manually popping the panels, when I first start with the PFD, I get the flypad...

**Comment by Rotorxdan** [comment]
Well... after trying several things, I seem to have found a work around to the problem. Before I start the pop out process, I press the mic button just below the EFB. That simply takes the EFB out of sight, and then the popout process just works normal. After that I enable the EFB again and connect to it remotely with an Ipad. Not straight forward but it works.

**Comment by hawkeye-stan** [comment]
It looks like EFB on Fenix is messing up pop out screen either through POPM or popping panels out manually. Wish I've Fenix to test to see what the actual technical issue is with this particular aircraft. Maybe the next version of Fenix will resolve this bug. Anyway, I'm glad you found a workaround.
